networks:
  echelon:
    external: true

services:
  test-ipv6-jenkins:
    container_name: test-ipv6-jenkins
    hostname: test-ipv6-jenkins
    networks:
      - echelon
    image: aprendendolinux/test-ipv6
    restart: always
    ports:
       - 8080:8080