networks:
  network-ipv6:
    driver: bridge
    enable_ipv6: true

services:
  test-ipv6:
    container_name: test-ipv6
    hostname: test-ipv6
    networks:
      - network-ipv6
    image: aprendendolinux/test-ipv6
    restart: always
    ports:
      - '8080:8080'
