networks:
  echelon:
    external: true

services:
  test-ipv6:
    container_name: test-ipv6
    hostname: test-ipv6
    networks:
      - echelon
    image: aprendendolinux/test-ipv6:latest
    restart: always
    # ports:
    #    - 8080:8080